"""Stable numeric slots for diagnostics schema 1; append-only within this schema."""

PROOF_METRICS = (
    "validation_rmse",
    "naive_rmse",
    "rank_fit",
    "baseline_rank_fit",
    "top_return",
    "top_uplift",
    "outcome_availability",
    "in_distribution_fraction",
    "policy_samples",
    "policy_observed",
    "policy_outcome_availability",
    "policy_supported",
    "policy_vetoes",
    "policy_winner_vetoes",
    "policy_winner_veto_fraction",
    "policy_mean_uplift",
    "policy_uplift_lower",
    "complexity_earned",
    "linear_validation_rmse",
    "evidence_schema_current",
    "policy_changes",
    "mean_uplift",
    "uplift_lower_bound",
    "harm_count",
    "harm_fraction",
    "selected_training_utility",
    "baseline_training_utility",
    "selected_validation_utility",
    "baseline_validation_utility",
    "validation_uplift_lower_bound",
    "validation_availability_fraction",
)
